version: '3'

services:
   db:
     image: mysql:5.7
     ports:
       - "3306:3306"
     volumes:
       - ~/Documents/IdeaProjects/springmicroservices/mysql_db_data:/var/lib/mysql # itemsharing_db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: itemsharing

# Created at /var/lib/docker/volumes/springmicroservices_itemsharing_db_data
#volumes:
#   itemsharing_db_data:
